name: base64_toolbox
description: A app to encode and decode everything.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  google_fonts:
  google_nav_bar:
  shared_preferences:
  material_design_icons_flutter:
  url_launcher:
  smooth_page_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
